### PR TITLE
Add `dependabot.yml`

### LINKED ISSUE #179: ENH: Setup dependabot
[Dependabot](https://github.blog/2020-06-01-keep-all-your-packages-up-to-date-with-dependabot/) automatically updates the version of packages for you. It can update both the python packages as well as any GH action packages. 

Basically, just copy [the file from the Epoch V onboarding](https://github.com/Jeffrey-Lim/onboarding-epoch-v/blob/main/.github/dependabot.yml).

### PR DESCRIPTION
**Pull request by Jeffrey-Lim**
Closes #179. A simple dependabot that monthly updates all Python packages and GitHub Actions

### CODE REVIEW

**Comment by schobbejak** [comment]
Add milestone to issue and check branch you are merging into next time

**Comment by schobbejak** [comment]
Why are there many other commits as well, don't create the branch from another one or main, use the version branches

**Comment by Jeffrey-Lim** [comment]
> Why are there many other commits as well, don't create the branch from another one or main, use the version branches

All these commits were from v.0.3.7. Merging that branch into v4.0.0 should fix it.

**Comment by schobbejak** [comment]
> > Why are there many other commits as well, don't create the branch from another one or main, use the version branches
> 
> All these commits were from v.0.3.7. Merging that branch into v4.0.0 should fix it.

Can only be done once the version is merged to main

**Comment by Jeffrey-Lim** [comment]
We can also just merge this into v0.3.7. A dependabot can't break anything on it's own and it's probably not even included in the `epochalyst` build.

**Comment by Jeffrey-Lim** [comment]
I've just merged `v4.0.0` to this branch and it's fixed

**Pull request merged**
