### PR TITLE
Fix logos broken on PyPi

### PR DESCRIPTION
**Pull request by Jeffrey-Lim**
Adds new SVG logos for light and dark mode and one for automatically switching between them based on your browser settings. The logo still appears to be broken as it now looks for the logo in `https://raw.githubusercontent.com/TeamEpochGithub/epochalyst/main/assets/`, but it should be fixed once this is merged. 

Because of that, I **intentionally** want to merge this into `main` first for testing purposes. I'm pretty sure it should work, but it's good to double-check. Then, we can merge this into the version branches.

### CODE REVIEW

**Comment by schobbejak** [comment]
Why do you need to merge it to main first, I don't get that

**Comment by Jeffrey-Lim** [comment]
> Why do you need to merge it to main first, I don't get that

I mean I guess I can also link the logos to `https://raw.githubusercontent.com/TeamEpochGithub/epochalyst/85-bug-logo-is-broken-on-pypi/assets/`, but this branch will get deleted after it's merged. Main is the only branch that will never be removed and thus the only suitable branch to link to. 

But I can try it anyway first. I'll change the link to tthis branch first, see if the readme looks good, and then I'll change it back to main again. If you really don't want to merge this to main, we don't have to, but it is the easiest way to verify that everything works.

**Comment by Jeffrey-Lim** [comment]
Also, what is the branch name check? Why do I need to rename it to a specific version?

**Comment by Jeffrey-Lim** [comment]
Alright, you can see [here](https://github.com/TeamEpochGithub/epochalyst/blob/6d9c8db1dbcf95272a0436a859f53ab7800db440/README.md) that it shows the logo correctly. Still can't verify it on PyPi, but it should be good there as well.  

I'm changing the link back to main. I leave it up to you if you actually want to merge this to main already to be really sure that it works, but it should be fine to merge into `v4.0.0` as long as we eventually merge this to main.

**Review by schobbejak — APPROVED** [review]

**Pull request merged**
